### ISSUE TITLE
Test involving many 6x6 matrices fails randomly on Mac OS

### ISSUE THREAD

**Issue by vihdzp** [bluss/matrixmultiply#55]
As part of a bigger project, I have some test code that multiplies matrices of various sizes over and over. One of the tests multiplies 6×6 matrices with one another over and over, about 200k times or so. Even though the test typically takes 15s to complete on other platforms, on Mac OS specifically, about half of the time, it panics on the following line at 2s: https://github.com/bluss/matrixmultiply/blob/9e4a11fba28d97d721433c32d517802aa19507cb/src/gemm.rs#L294
Here's a [link](https://github.com/OfficialURL/miratope-rs/runs/2287904877) to the backtrace in one specific run where it failed.

I'm using [`nalgebra`](https://github.com/dimforge/nalgebra) as a dependency, but due to the OS specific nature of the bug, I've discarded it being a bug over there. I haven't been able to isolate exactly how to reproduce this bug, but hopefully the backtrace helps to that avail.

**Comment by OfficialURL** [comment]
I added the 6×6 matrix case to a few other tests. Sure enough, one of them failed again on the (last run)[https://github.com/OfficialURL/miratope-rs/runs/2288160444]. So this suggests the problem is specifically with multiplying 6×6 matrices (and maybe matrices of a few other sizes). I'll try to isolate a more specific failing example using this.

**Comment by bluss** [comment]
Ok, that's mysterious. Which feature flags is the crate compiled with? Thanks.

**Comment by OfficialURL** [comment]
Just the default features. Specifically, `nalgebra` has this line in its Cargo.toml:

```toml
matrixmultiply = { version = "0.3", optional = true }
```

**Comment by OfficialURL** [comment]
I'm currently attempting (but failing) to reproduce this bug in a new repository: https://github.com/OfficialURL/matrixmultiply-test

**Comment by bluss** [comment]
It seems to be about the alignment of the mask buffer. New in 0.3.0 is that we're using `#[repr(align(32))]` for it.

1. We're doing it wrong (?)
2. Thread local storage can't allocate with alignment properly (on macos)?
3. Other

Since it's about the location/allocation of thread local storage, it should be attempted to reproduce it by many executions and preferably calling from multiple threads. The defaults in the rust test runner are multithreaded.

Because it's a debug assertion, it won't fire if debug assertions are turned off, but we should use avx registers that require this 32-byte alignment, so it should crash with a more cryptic error in release mode(?)

**Comment by bluss** [comment]
There seems to be some interesting information in https://github.com/rust-lang/rust/pull/51828/files#diff-8fde2ea720eeecb2220536a749a0ff7b86e5242c2db1fd5fecbc6074aa544ce2R313-R332  but it's a lot to digest

**Comment by OfficialURL** [comment]
Weirdly, the code in the repo where the bug originated doesn't seem to fail anymore when the `--release` flag is specified on the tests. At the very least, the last two tests have been successful. This might be a fluke, so I'll keep testing.

**Comment by bluss** [comment]
It's not uncommon that alignment of allocations changes with optimizations.

**Comment by bluss** [comment]
If you don't mind, let's ask on the user forum or discord? Unless you already have

**Comment by bluss** [comment]
Oh great. If we can reproduce it I'm sure we can fix it. I don't have access to any macs right now. Contributors adding macos support to CI are welcome by the way.

I'll ask on the Rust forum.

**Comment by bluss** [comment]
There is a branch/pr to test in #56. If it works, I can release it. :slightly_smiling_face:

**Comment by eddyb** [comment]
@vihdzp See https://github.com/rust-lang/rust/issues/90959#issuecomment-1000817211 - but I'm not sure if there's any way to check what linker is used in CI, short of adding a command like this to the CI workflow:
```sh
echo 'fn main() {}' | rustc - -C link-args=-Wl,--this-flag-does-not-exist
```
which on linux produces something like this (`cc` command-line mostly omitted for brevity):
```
error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-m64" ... "-Wl,--this-flag-does-not-exist"
  = note: ld: unrecognized option '--this-flag-does-not-exist'
          ld: use the --help option for usage information
          clang-6.0: error: linker command failed with exit code 1 (use -v to see invocation)
```
Alternatively, if that doesn't distinguish between `ld64` and `lld`/`ld64.lld`, this might:
```sh
echo 'int main() {}' | cc -v -x c - 2>&1 | tail -n1
```

**Comment by bluss** [comment]
This seems to be back due to new debug assertions in std
