### ISSUE TITLE
ref_mat_mul not always the slower version

### ISSUE THREAD

**Issue by petevine** [bluss/matrixmultiply#6]
I'm getting these results on ARM, NEON:

```go
running 18 tests
test mat_mul_f32::m004     ... bench:       2,026 ns/iter (+/- 198)
test mat_mul_f32::m005     ... bench:       2,852 ns/iter (+/- 112)
test mat_mul_f32::m006     ... bench:       2,955 ns/iter (+/- 55)
test mat_mul_f32::m007     ... bench:       3,191 ns/iter (+/- 85)
test mat_mul_f32::m008     ... bench:       3,404 ns/iter (+/- 89)
test mat_mul_f32::m009     ... bench:       6,722 ns/iter (+/- 313)
test mat_mul_f32::m012     ... bench:       8,575 ns/iter (+/- 1,451)
test mat_mul_f32::m016     ... bench:      12,836 ns/iter (+/- 255)
test mat_mul_f32::m032     ... bench:      72,610 ns/iter (+/- 3,202)

test ref_mat_mul_f32::m004 ... bench:         611 ns/iter (+/- 7)
test ref_mat_mul_f32::m005 ... bench:       1,076 ns/iter (+/- 28)
test ref_mat_mul_f32::m006 ... bench:       1,745 ns/iter (+/- 28)
test ref_mat_mul_f32::m007 ... bench:       2,653 ns/iter (+/- 142)
test ref_mat_mul_f32::m008 ... bench:       3,871 ns/iter (+/- 81)
test ref_mat_mul_f32::m009 ... bench:       5,705 ns/iter (+/- 133)
test ref_mat_mul_f32::m012 ... bench:      12,146 ns/iter (+/- 237)
test ref_mat_mul_f32::m016 ... bench:      27,906 ns/iter (+/- 1,232)
test ref_mat_mul_f32::m032 ... bench:     213,525 ns/iter (+/- 4,080)
````

Coming from `ver 0.1.6`

**Comment by bluss** [comment]
Thank you for the report!

The benchmarks for the small sizes absolutely exist so that we can look at the overhead. The primary focus of the library is for much larger matrices, but it would be ideal if we could have it always be fast.

It could be that the allocation of the packing buffers is a large overhead on that platform, the numbers sort of suggest a large fixed overhead.

sandy bridge/avx/linux looks something like this, and breaks even already with 6x6 matrices or so. (A much lower overhead than what I expected.)

```rust
test mat_mul_f32::m004             ... bench:         173 ns/iter (+/- 5)
test ref_mat_mul_f32::m004         ... bench:          90 ns/iter (+/- 6)

test mat_mul_f32::m006             ... bench:         250 ns/iter (+/- 3)
test ref_mat_mul_f32::m006         ... bench:         241 ns/iter (+/- 6)

test mat_mul_f32::m007             ... bench:         271 ns/iter (+/- 147)
test ref_mat_mul_f32::m007         ... bench:         341 ns/iter (+/- 6)

test mat_mul_f32::m008             ... bench:         294 ns/iter (+/- 6)
test ref_mat_mul_f32::m008         ... bench:         506 ns/iter (+/- 27)
```

**Comment by petevine** [comment]
And on i686 (Core2) it seem to happen with 7x7:

```go
test mat_mul_f32::m004     ... bench:         365 ns/iter (+/- 5)
test mat_mul_f32::m005     ... bench:         500 ns/iter (+/- 4)
test mat_mul_f32::m006     ... bench:         540 ns/iter (+/- 7)
test mat_mul_f32::m007     ... bench:         598 ns/iter (+/- 14)
test mat_mul_f32::m008     ... bench:         610 ns/iter (+/- 8)
test mat_mul_f32::m009     ... bench:       1,172 ns/iter (+/- 20)
test mat_mul_f32::m012     ... bench:       1,483 ns/iter (+/- 50)
test mat_mul_f32::m016     ... bench:       2,268 ns/iter (+/- 14)
test mat_mul_f32::m032     ... bench:      11,528 ns/iter (+/- 49)

test ref_mat_mul_f32::m004 ... bench:         145 ns/iter (+/- 0)
test ref_mat_mul_f32::m005 ... bench:         267 ns/iter (+/- 0)
test ref_mat_mul_f32::m006 ... bench:         410 ns/iter (+/- 2)
test ref_mat_mul_f32::m007 ... bench:         610 ns/iter (+/- 0)
test ref_mat_mul_f32::m008 ... bench:         840 ns/iter (+/- 8)
test ref_mat_mul_f32::m009 ... bench:       1,310 ns/iter (+/- 28)
test ref_mat_mul_f32::m012 ... bench:       2,951 ns/iter (+/- 122)
test ref_mat_mul_f32::m016 ... bench:       6,714 ns/iter (+/- 15)
test ref_mat_mul_f32::m032 ... bench:      47,847 ns/iter (+/- 138)
````

**Comment by bluss** [comment]
I think we can relatively easy switch from allocating two vectors to allocating just one and splitting it between packed A and packed B. You see how low the allocation overhead is on the intel/linux platforms, so any stack allocated array solutions I've tried have only been worse.

**Comment by petevine** [comment]
If you cared to drop by in this [llvm issue](https://llvm.org/bugs/show_bug.cgi?id=27103) that would surely help. Thanks.

**Comment by bluss** [comment]
The code in this library is just written in whatever shape I could find that autovectorized well for my platform. It's not super surprising if this doesn't translate well to other platforms.

Please don't go overboard with the microbenchmarks of the smaller sizes of matrix multiplications.

The microkernel function for the f32 multiplication uses a working size of shape 4 by 8, which means that all the input has to be padded to multiples of those sizes (4 and 8 respectively). Because of that it's not weird if you see irregular patterns when comparing sizes.

A 7x7 times 7x7 multiplication will be padded out to a 8x7 times 7x8 for example. A 3x3 times 3x3 multiplication will be padded out to 4x3 times 3x8 and so on.

**Comment by bluss** [comment]
Oh by the way, another threshold at 8 is that the sgemm kernel is unrolled by 8. For 8x8 times 8x8 that means it runs the computation in one unrolled line of code, for the m007 case, it runs the tail end loop 7 times instead. That's probably the main explanation for the difference of m007 vs m008 for f32.

**Comment by bluss** [comment]
I can understand the bewilderment of llvm devs if given something like this. Better to use a reduced example.

**Comment by petevine** [comment]
That `m007 vs m008` was the original result from `0.1.0`, afterwards it's super regular.

**Comment by bluss** [comment]
aha, I didn't notice the dates.

**Comment by bluss** [comment]
I don't know what I can say for that issue more than I didn't write this code with NEON in mind, and I can't test it there.

**Comment by bluss** [comment]
Meanwhile, I'm going to explore the two vs one allocations issue.

**Comment by petevine** [comment]
Thanks for the info; the reason I brought it up over there was the old "intelligent compiler" hope :)

**Comment by bluss** [comment]
PR #7 gave a small speedup for all the small cases by reducing allocation overhead.

What can we do with this issue to turn it into something actionable? I'm grateful for the sharing of benchmarks from platforms I don't have access to.

There's a number of things that can be done to tune/tweak the library for each arch if we wanted to do that, first thing that comes to mind is src/archparams.rs, but also the microkernels themselves.

**Comment by petevine** [comment]
I believe this issue can be safely closed as the overhead has been clearly identified and some improvement posted.

Platform specific optimizations would be nice of course :) Conversely, to test the compiler's smarts, a truly platform agnostic, naive algorithm might be an idea.

**Comment by bluss** [comment]
Ok, great. Overhead was reduced somewhat. New issues always welcome.

**Comment by bluss** [comment]
The algorithm is platform agnostic in the sense that it computes the correct result in portable Rust.

But there's a lot of parameters that are explicitly chosen to suit the platform.

Packing buffers for A and B are chosen so that they fit in L2 and L3 cache respectively. Microkernels need to pick a register size and implement for that (for example 2x2, 4x4 or the current ones use 4x8 and 8x4).
